type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Hotel @table {
  name: String!
  address: String
  stars: Int
}

type Tour @table {
  country: String!
  city: String!
  departureDate: Date!
  returnDate: Date!
  price: Float!
  hotel: Hotel!
  imageUrl: String
}

type Review @table {
  user: User!
  tour: Tour!
  rating: Int!
  text: String
  createdAt: Timestamp!
}
