name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Необходимо для аутентификации в Google Cloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/77706967342/locations/global/workloadIdentityPools/1235465465123123/providers/234523546234562452456'
          service_account: 'firebase-app-hosting-compute@biblioglobustourweaveapp.iam.gserviceaccount.com'

      - name: Deploy to Firebase App Hosting
        uses: firebase-actions/deploy-app-hosting@v0
        with:
          projectId: 'biblioglobustourweaveapp'
          siteId: 'studio' # ID вашего бэкенда в App Hosting