name: Firebase App Hosting CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.MY_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.MY_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.MY_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.MY_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MY_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.MY_FIREBASE_APP_ID }}
      GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
      BIBLIO_GLOBUS_LOGIN: ${{ secrets.BIBLIO_GLOBUS_LOGIN }}
      BIBLIO_GLOBUS_PASSWORD: ${{ secrets.BIBLIO_GLOBUS_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Enable webframeworks experiment
        run: npx firebase-tools experiments:enable webframeworks

      - name: Setup Firebase credentials
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/google-credentials.json
      
      - name: Deploy to Firebase Preview Channel
        if: github.event_name == 'pull_request'
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-credentials.json
          npx firebase-tools hosting:channel:deploy pr-${{ github.event.number }} --expires 7d --project ${{ secrets.FIREBASE_PROJECT_ID }} --json

      - name: Deploy to Firebase Live Channel
        if: github.ref == 'refs/heads/main'
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-credentials.json
          npx firebase-tools deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --json
          
          